FROM node:19.9.0-alpine as builder

WORKDIR /usr/src/app

COPY frontend/package.json ./

RUN npm install

COPY ./frontend .

# RUN npm run build

FROM nginx:1.25.0 AS prod-build

COPY frontend/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
