FROM python:3.9

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100

# System dependencies
RUN pip install poetry

# Copy requirements to cache them in docker layer
WORKDIR /usr/src/app
COPY backend/pyproject.toml backend/poetry.lock ./

# Project initialization:
RUN poetry config virtualenvs.create false \
  && poetry install --no-root

COPY ./backend .

RUN python manage.py collectstatic
